# Generated by Django 4.0.8 on 2022-12-14 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
